-- Fire Safety Analytics: Database Schema
-- PostgreSQL
-- 8 tables: 4 catalog dimension tables (loaded from CSV) + 4 synthetic operations tables

-- ============================================================
-- Catalog dimension tables (loaded from data/*.csv)
-- ============================================================

CREATE TABLE categories (
    category_id INT PRIMARY KEY,
    category_name VARCHAR(100),
    description VARCHAR(500)
);

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    category_id INT REFERENCES categories(category_id),
    product_name VARCHAR(100)
);

CREATE TABLE sectors (
    sector_id INT PRIMARY KEY,
    sector_name VARCHAR(100),
    description VARCHAR(500)
);

CREATE TABLE industries (
    industry_id INT PRIMARY KEY,
    sector_id INT REFERENCES sectors(sector_id),
    industry_name VARCHAR(100)
);

-- ============================================================
-- Synthetic operations tables (generated by scripts/*.py)
-- ============================================================

CREATE TABLE plants (
    plant_id SERIAL PRIMARY KEY,
    plant_name VARCHAR(50),
    country VARCHAR(50)
);

INSERT INTO plants (plant_name, country) VALUES
('Plant A', 'Germany'),
('Plant B', 'Germany'),
('Plant C', 'Singapore');

CREATE TABLE production_batches (
    batch_id SERIAL PRIMARY KEY,
    product_id INT REFERENCES products(product_id),
    plant_id INT REFERENCES plants(plant_id),
    production_date DATE,
    quantity_produced INT,
    defect_qty INT
);

CREATE TABLE orders (
    order_id SERIAL PRIMARY KEY,
    product_id INT REFERENCES products(product_id),
    industry_id INT REFERENCES industries(industry_id),
    order_date DATE,
    requested_ship_date DATE,
    actual_ship_date DATE,
    quantity INT,
    destination_country VARCHAR(50)
);

CREATE TABLE inventory_snapshots (
    snapshot_id SERIAL PRIMARY KEY,
    snapshot_date DATE,
    product_id INT REFERENCES products(product_id),
    plant_id INT REFERENCES plants(plant_id),
    stock_qty INT,
    reorder_level INT
);
